/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CodeSymbol {
  name: string
  kind: string
  start: SourceLocation
  end: SourceLocation
  signature: string
}

export interface FileReport {
  path: string
  language: string
  sizeBytes: number
  symbols: Array<CodeSymbol>
  error?: string
}

export declare function scanProject(rootPath: string): ScanResult

export interface ScanResult {
  rootDir: string
  durationMs: number
  filesScanned: number
  files: Array<FileReport>
}

export interface SourceLocation {
  row: number
  column: number
}
